---
  kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    name: aureliacomponentgallery
    namespace: websites
  spec:
    template:
      metadata:
        labels:
          name: aureliacomponentgallery
      spec:
        containers:
        - name: aureliacomponentgallery
          image: dolittle/components.aurelia.gallery
          imagePullPolicy: Always
          ports:
          - containerPort: 80
            name: http
          resources:
            limits:
              cpu: 250m
              memory: 100Mi          
